package main
import("crypto/rand";"crypto/sha256";"encoding/base64";"encoding/hex";"encoding/json";"fmt";"io";"io/fs";"log";"mime";"net/http";"os";"path/filepath";"sort";"strings";"sync";"time";"github.com/pquerna/otp/totp";"github.com/skip2/go-qrcode";"golang.org/x/crypto/bcrypt")
type FI struct{Path string `json:"path"`;Size int64 `json:"size"`;MTime int64 `json:"mtime"`;Hash string `json:"hash"`;Kind string `json:"kind"`};type Change struct{Revision int64 `json:"revision"`;Device,Op,Path string;TS int64 `json:"ts"`};type Device struct{LastSeen,LastRevision int64};type Admin struct{User,PasswordHash,TOTPSecret string;Recovery map[string]bool};type State struct{Revision int64;Token string;Devices map[string]Device;Tombstones map[string]Change;Journal []Change;Admin *Admin};type Session struct{Expires int64};type LoginChallenge struct{User string;Expires int64};type App struct{root,data,statePath,trash string;mu sync.Mutex;s State;sessions map[string]Session;challenges map[string]int64;loginChallenges map[string]LoginChallenge}
type CM struct{Device string `json:"device"`;LastRevision int64 `json:"last_revision"`;Files []FI `json:"files"`;Deleted []string `json:"deleted"`;Baseline map[string]string `json:"baseline"`}
func main(){root:="./vault";if v:=os.Getenv("VAULT_DIR");v!=""{root=v};data:="./sync-data";os.MkdirAll(root,0755);os.MkdirAll(data,0700);a:=&App{root:root,data:data,statePath:filepath.Join(data,"state.json"),trash:filepath.Join(data,"trash"),sessions:map[string]Session{},challenges:map[string]int64{},loginChallenges:map[string]LoginChallenge{}};a.load();m:=http.NewServeMux();m.HandleFunc("/api/auth/state",a.authState);m.HandleFunc("/api/auth/setup/start",a.setupStart);m.HandleFunc("/api/auth/setup/finish",a.setupFinish);m.HandleFunc("/api/auth/login/start",a.loginStart);m.HandleFunc("/api/auth/login/verify",a.loginVerify);m.HandleFunc("/api/auth/logout",a.logout);m.HandleFunc("/health",a.health);m.HandleFunc("/api/files",a.webAuth(a.files));m.HandleFunc("/api/file",a.webAuth(a.webFile));m.HandleFunc("/api/folder",a.webAuth(a.folder));m.HandleFunc("/api/asset",a.webAuth(a.asset));m.HandleFunc("/api/resolve",a.webAuth(a.resolve));m.HandleFunc("/api/manifest",a.webAuth(a.manifest));m.HandleFunc("/api/admin/status",a.webAuth(a.adminStatus));m.HandleFunc("/api/admin/trash",a.webAuth(a.trashList));m.HandleFunc("/api/sync/reconcile",a.syncAuth(a.reconcile));m.HandleFunc("/api/sync/file",a.syncAuth(a.syncFile));m.HandleFunc("/api/sync/conflict",a.syncAuth(a.conflict));m.Handle("/",http.FileServer(http.Dir("./web")));log.Printf("v8.1 http://0.0.0.0:8080 vault=%s",root);log.Printf("sync token: %s",a.s.Token);if a.s.Admin==nil{code:=random(12);os.WriteFile(filepath.Join(data,"setup-code"),[]byte(code),0600);log.Printf("FIRST RUN setup code: %s",code)};log.Fatal(http.ListenAndServe(":8080",m))}
func random(n int)string{b:=make([]byte,n);rand.Read(b);return hex.EncodeToString(b)[:n]};func(a *App)load(){a.s=State{Revision:1,Token:random(48),Devices:map[string]Device{},Tombstones:map[string]Change{},Journal:[]Change{}};if b,e:=os.ReadFile(a.statePath);e==nil{json.Unmarshal(b,&a.s)};if a.s.Token==""{a.s.Token=random(48)};if a.s.Devices==nil{a.s.Devices=map[string]Device{}};if a.s.Tombstones==nil{a.s.Tombstones=map[string]Change{}};a.save()};func(a *App)save(){b,_:=json.MarshalIndent(a.s,"","  ");os.WriteFile(a.statePath+".tmp",b,0600);os.Rename(a.statePath+".tmp",a.statePath)}
func safe(root,p string)(string,error){p=strings.TrimPrefix(filepath.Clean("/"+p),"/");if p==""||p=="."{return"",fmt.Errorf("bad path")};q:=filepath.Join(root,p);r,_:=filepath.Abs(root);x,_:=filepath.Abs(q);if !strings.HasPrefix(x,r+string(os.PathSeparator)){return"",fmt.Errorf("bad path")};return q,nil};func kind(p string)string{e:=strings.ToLower(filepath.Ext(p));if e==".md"{return"markdown"};if e==".pdf"{return"pdf"};if e==".png"||e==".jpg"||e==".jpeg"||e==".gif"||e==".webp"{return"image"};return"other"};func hash(p string)(string,error){f,e:=os.Open(p);if e!=nil{return"",e};defer f.Close();h:=sha256.New();_,e=io.Copy(h,f);return hex.EncodeToString(h.Sum(nil)),e};func(a *App)scan()(o []FI,e error){e=filepath.WalkDir(a.root,func(p string,d fs.DirEntry,er error)error{if er!=nil{return er};if d.IsDir(){return nil};rel,_:=filepath.Rel(a.root,p);i,_:=d.Info();h,er:=hash(p);if er!=nil{return er};o=append(o,FI{filepath.ToSlash(rel),i.Size(),i.ModTime().UnixMilli(),h,kind(p)});return nil});sort.Slice(o,func(i,j int)bool{return o[i].Path<o[j].Path});return};func jout(w http.ResponseWriter,v any){w.Header().Set("Content-Type","application/json");json.NewEncoder(w).Encode(v)};func(a *App)bump(dev,op,path string)int64{a.s.Revision++;a.s.Journal=append(a.s.Journal,Change{a.s.Revision,dev,op,path,time.Now().UnixMilli()});if len(a.s.Journal)>100000{a.s.Journal=a.s.Journal[len(a.s.Journal)-100000:]};a.save();return a.s.Revision}
func(a *App)syncAuth(n http.HandlerFunc)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){if r.Header.Get("Authorization")!="Bearer "+a.s.Token{http.Error(w,"unauthorized",401);return};n(w,r)}};func(a *App)webAuth(n http.HandlerFunc)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){c,e:=r.Cookie("msh_session");if e!=nil{http.Error(w,"login required",401);return};s,ok:=a.sessions[c.Value];if !ok||s.Expires<time.Now().Unix(){http.Error(w,"session expired",401);return};n(w,r)}}
func(a *App)authState(w http.ResponseWriter,r *http.Request){jout(w,map[string]any{"configured":a.s.Admin!=nil})}

// setupStart: validates the setup code, generates a TOTP secret and returns it with a base64 PNG QR code.
func(a *App)setupStart(w http.ResponseWriter,r *http.Request){
	if a.s.Admin!=nil{http.Error(w,"configured",403);return}
	var q struct{Code,User,Password string}
	json.NewDecoder(r.Body).Decode(&q)
	b,_:=os.ReadFile(filepath.Join(a.data,"setup-code"))
	if strings.TrimSpace(string(b))!=q.Code||len(q.Password)<10{http.Error(w,"invalid setup",403);return}
	k,err:=totp.Generate(totp.GenerateOpts{Issuer:"Markdown Sync Hub",AccountName:q.User})
	if err!=nil{http.Error(w,"totp failed",500);return}
	id:=random(24)
	a.challenges[id]=time.Now().Add(10*time.Minute).Unix()
	png,err:=qrcode.Encode(k.URL(),qrcode.Medium,256)
	if err!=nil{http.Error(w,"qr failed",500);return}
	qr:=base64.StdEncoding.EncodeToString(png)
	jout(w,map[string]any{"setup_id":id,"secret":k.Secret(),"otpauth":k.URL(),"qr":qr,"user":q.User,"password":q.Password})
}

func(a *App)setupFinish(w http.ResponseWriter,r *http.Request){if a.s.Admin!=nil{return};var q struct{SetupID,User,Password,Secret,Code string};json.NewDecoder(r.Body).Decode(&q);if a.challenges[q.SetupID]<time.Now().Unix()||!totp.Validate(q.Code,q.Secret){http.Error(w,"invalid",403);return};ph,_:=bcrypt.GenerateFromPassword([]byte(q.Password),bcrypt.DefaultCost);rec:=map[string]bool{};codes:=[]string{};for i:=0;i<8;i++{c:=random(12);rec[hexHash(c)]=true;codes=append(codes,c)};a.s.Admin=&Admin{q.User,string(ph),q.Secret,rec};a.save();os.Remove(filepath.Join(a.data,"setup-code"));delete(a.challenges,q.SetupID);jout(w,map[string]any{"ok":true,"recovery_codes":codes})};func hexHash(s string)string{h:=sha256.Sum256([]byte(s));return hex.EncodeToString(h[:])}

// loginStart: step 1. Checks username + password, returns a short-lived login_id.
func(a *App)loginStart(w http.ResponseWriter,r *http.Request){
	if a.s.Admin==nil{http.Error(w,"setup required",403);return}
	var q struct{User,Password string}
	json.NewDecoder(r.Body).Decode(&q)
	if q.User!=a.s.Admin.User||bcrypt.CompareHashAndPassword([]byte(a.s.Admin.PasswordHash),[]byte(q.Password))!=nil{http.Error(w,"invalid",401);return}
	id:=random(32)
	a.loginChallenges[id]=LoginChallenge{User:q.User,Expires:time.Now().Add(5*time.Minute).Unix()}
	jout(w,map[string]any{"login_id":id})
}

// loginVerify: step 2. Checks the login_id plus a TOTP code or one-time recovery code, then issues the session cookie.
// The login_id is single-use: it is consumed whether or not the code is correct.
func(a *App)loginVerify(w http.ResponseWriter,r *http.Request){
	if a.s.Admin==nil{http.Error(w,"setup required",403);return}
	var q struct{LoginID string `json:"login_id"`;Code string `json:"code"`}
	json.NewDecoder(r.Body).Decode(&q)
	ch,found:=a.loginChallenges[q.LoginID]
	delete(a.loginChallenges,q.LoginID)
	if !found||ch.Expires<time.Now().Unix()||ch.User!=a.s.Admin.User{http.Error(w,"invalid",401);return}
	ok:=totp.Validate(q.Code,a.s.Admin.TOTPSecret)
	if !ok&&a.s.Admin.Recovery[hexHash(q.Code)]{
		delete(a.s.Admin.Recovery,hexHash(q.Code))
		a.save()
		ok=true
	}
	if !ok{http.Error(w,"invalid",401);return}
	sid:=random(64)
	a.sessions[sid]=Session{time.Now().Add(12*time.Hour).Unix()}
	http.SetCookie(w,&http.Cookie{Name:"msh_session",Value:sid,Path:"/",HttpOnly:true,Secure:r.Header.Get("X-Forwarded-Proto")=="https"||r.TLS!=nil,SameSite:http.SameSiteStrictMode,MaxAge:43200})
	jout(w,map[string]bool{"ok":true})
}

func(a *App)logout(w http.ResponseWriter,r *http.Request){if c,e:=r.Cookie("msh_session");e==nil{delete(a.sessions,c.Value)};http.SetCookie(w,&http.Cookie{Name:"msh_session",Path:"/",MaxAge:-1,HttpOnly:true});jout(w,map[string]bool{"ok":true})}
func(a *App)health(w http.ResponseWriter,r *http.Request){jout(w,map[string]any{"status":"ok","version":"7.0","revision":a.s.Revision})};func(a *App)files(w http.ResponseWriter,r *http.Request){x,e:=a.scan();if e!=nil{http.Error(w,e.Error(),500);return};jout(w,x)};func(a *App)webFile(w http.ResponseWriter,r *http.Request){n:=r.URL.Query().Get("path");p,e:=safe(a.root,n);if e!=nil||!strings.EqualFold(filepath.Ext(n),".md"){http.Error(w,"bad",400);return};if r.Method=="GET"{http.ServeFile(w,r,p);return};if r.Method=="PUT"{b,_:=io.ReadAll(io.LimitReader(r.Body,16<<20));os.MkdirAll(filepath.Dir(p),0755);os.WriteFile(p,b,0644);a.mu.Lock();a.bump("web","UPDATE",n);delete(a.s.Tombstones,n);a.save();a.mu.Unlock();jout(w,map[string]bool{"ok":true});return};http.Error(w,"method",405)};func(a *App)folder(w http.ResponseWriter,r *http.Request){var q struct{Path string};json.NewDecoder(r.Body).Decode(&q);p,e:=safe(a.root,q.Path);if e!=nil{http.Error(w,"bad",400);return};os.MkdirAll(p,0755);jout(w,map[string]bool{"ok":true})};func(a *App)asset(w http.ResponseWriter,r *http.Request){p,e:=safe(a.root,r.URL.Query().Get("path"));if e!=nil||(kind(p)!="image"&&kind(p)!="pdf"){http.Error(w,"bad",400);return};w.Header().Set("Content-Disposition","inline");if t:=mime.TypeByExtension(filepath.Ext(p));t!=""{w.Header().Set("Content-Type",t)};http.ServeFile(w,r,p)};func(a *App)resolve(w http.ResponseWriter,r *http.Request){name:=filepath.Base(r.URL.Query().Get("name"));h:=[]string{};filepath.WalkDir(a.root,func(p string,d fs.DirEntry,e error)error{if e==nil&&!d.IsDir()&&strings.EqualFold(filepath.Base(p),name){x,_:=filepath.Rel(a.root,p);h=append(h,filepath.ToSlash(x))};return nil});jout(w,map[string]any{"matches":h})};func(a *App)manifest(w http.ResponseWriter,r *http.Request){x,_:=a.scan();jout(w,map[string]any{"revision":a.s.Revision,"files":x})};func(a *App)adminStatus(w http.ResponseWriter,r *http.Request){jout(w,map[string]any{"revision":a.s.Revision,"devices":a.s.Devices,"journal":a.s.Journal[max(0,len(a.s.Journal)-50):],"tombstones":a.s.Tombstones})};func max(a,b int)int{if a>b{return a};return b};func(a *App)trashList(w http.ResponseWriter,r *http.Request){o:=[]string{};filepath.WalkDir(a.trash,func(p string,d fs.DirEntry,e error)error{if e==nil&&!d.IsDir(){x,_:=filepath.Rel(a.trash,p);o=append(o,filepath.ToSlash(x))};return nil});jout(w,o)}
func(a *App)moveTrash(path string)bool{p,e:=safe(a.root,path);if e!=nil{return false};if _,e=os.Stat(p);e!=nil{return false};d:=filepath.Join(a.trash,time.Now().Format("20060102-150405.000"),filepath.FromSlash(path));os.MkdirAll(filepath.Dir(d),0700);return os.Rename(p,d)==nil};func(a *App)reconcile(w http.ResponseWriter,r *http.Request){var q CM;if json.NewDecoder(r.Body).Decode(&q)!=nil{return};a.mu.Lock();defer a.mu.Unlock();for _,p:=range q.Deleted{if a.moveTrash(p){v:=a.bump(q.Device,"DELETE",p);a.s.Tombstones[p]=Change{v,q.Device,"DELETE",p,time.Now().UnixMilli()}}};sv,_:=a.scan();sm,cm:=map[string]FI{},map[string]FI{};for _,f:=range sv{sm[f.Path]=f};for _,f:=range q.Files{cm[f.Path]=f};same,down,up,conf,del:=[]string{},[]string{},[]string{},[]string{},[]string{};for p,s:=range sm{c,ok:=cm[p];if !ok{down=append(down,p);continue};if c.Hash==s.Hash{same=append(same,p);continue};b,ok:=q.Baseline[p];if !ok||b==""{conf=append(conf,p)}else if c.Hash==b{down=append(down,p)}else if s.Hash==b{up=append(up,p)}else{conf=append(conf,p)}};for p:=range cm{if _,ok:=sm[p];!ok{if _,dead:=a.s.Tombstones[p];dead{del=append(del,p)}else{up=append(up,p)}}};a.s.Devices[q.Device]=Device{time.Now().UnixMilli(),q.LastRevision};a.save();jout(w,map[string]any{"revision":a.s.Revision,"same":same,"download":down,"upload":up,"delete":del,"conflict":conf})};func(a *App)syncFile(w http.ResponseWriter,r *http.Request){dev,n:=r.URL.Query().Get("device"),r.URL.Query().Get("path");p,e:=safe(a.root,n);if e!=nil{return};if r.Method=="GET"{http.ServeFile(w,r,p);return};if r.Method=="PUT"{b,_:=io.ReadAll(io.LimitReader(r.Body,128<<20));os.MkdirAll(filepath.Dir(p),0755);os.WriteFile(p,b,0644);a.mu.Lock();a.bump(dev,"UPDATE",n);delete(a.s.Tombstones,n);a.save();a.mu.Unlock();jout(w,map[string]bool{"ok":true})}};func(a *App)conflict(w http.ResponseWriter,r *http.Request){dev,n:=r.URL.Query().Get("device"),r.URL.Query().Get("path");ext:=filepath.Ext(n);cn:=strings.TrimSuffix(n,ext)+".conflict-"+dev+"-"+time.Now().Format("20060102-150405")+ext;p,e:=safe(a.root,cn);if e!=nil{return};b,_:=io.ReadAll(r.Body);os.MkdirAll(filepath.Dir(p),0755);os.WriteFile(p,b,0644);a.mu.Lock();a.bump(dev,"CONFLICT_COPY",cn);a.mu.Unlock();jout(w,map[string]string{"path":cn})}
