import {App,Notice,Plugin,PluginSettingTab,Setting,TFile,requestUrl,normalizePath} from 'obsidian';
interface Settings{server:string;token:string;device:string;interval:number;startup:boolean}
const DEF:Settings={server:'http://127.0.0.1:8080',token:'',device:'obsidian',interval:0,startup:true};
async function sha(b:ArrayBuffer){const h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}
export default class Hub extends Plugin{
 settings:Settings=DEF;syncing=false;timer:number|null=null;status:any;
 async onload(){const d:any=await this.loadData()||{};this.settings=Object.assign({},DEF,d);this.status=this.addStatusBarItem();this.setStatus('idle');this.addRibbonIcon('refresh-cw','Markdown Sync Hub: Sync',()=>this.sync());this.addCommand({id:'sync-now',name:'Sync now',callback:()=>this.sync()});this.addSettingTab(new Tab(this.app,this));this.startTimer();if(this.settings.startup)this.app.workspace.onLayoutReady(()=>this.sync())}
 setStatus(s:string){this.status?.setText('Sync '+s)}
 startTimer(){if(this.timer)window.clearInterval(this.timer);if(this.settings.interval>0)this.timer=window.setInterval(()=>this.sync(),this.settings.interval*60000)}
 async api(p:string,m='GET',b?:any){return requestUrl({url:this.settings.server.replace(/\/$/,'')+p,method:m,headers:{Authorization:'Bearer '+this.settings.token,'Content-Type':'application/json'},body:b===undefined?undefined:(b instanceof ArrayBuffer?b:JSON.stringify(b)),throw:false})}
 async manifest(){const a:any[]=[];for(const f of this.app.vault.getFiles()){if(f.path.startsWith('.obsidian/'))continue;const b=await this.app.vault.readBinary(f);a.push({path:f.path,size:f.stat.size,mtime:f.stat.mtime,hash:await sha(b),kind:f.extension==='md'?'markdown':'other'})}return a}
 async hashes(){const o:Record<string,string>={};for(const f of this.app.vault.getFiles()){if(f.path.startsWith('.obsidian/'))continue;o[f.path]=await sha(await this.app.vault.readBinary(f))}return o}
 async parent(p:string){let cur='';for(const x of p.split('/').slice(0,-1)){cur=cur?cur+'/'+x:x;if(!this.app.vault.getAbstractFileByPath(cur))await this.app.vault.createFolder(cur)}}
 async sync(){if(this.syncing||!this.settings.token)return;this.syncing=true;this.setStatus('syncing');try{const d:any=await this.loadData()||{},base:Record<string,string>=d.baseline||{},now=await this.hashes(),deleted=Object.keys(base).filter(p=>!(p in now));const rr=await this.api('/api/sync/reconcile','POST',{device:this.settings.device,last_revision:d.lastRevision||0,files:await this.manifest(),deleted,baseline:base});if(rr.status!==200)throw new Error(rr.text);const plan=rr.json;for(const p of plan.download){const r=await this.api('/api/sync/file?device='+encodeURIComponent(this.settings.device)+'&path='+encodeURIComponent(p));await this.parent(p);const f=this.app.vault.getAbstractFileByPath(p);if(f instanceof TFile)await this.app.vault.modifyBinary(f,r.arrayBuffer);else await this.app.vault.createBinary(normalizePath(p),r.arrayBuffer)}for(const p of plan.upload){const f=this.app.vault.getAbstractFileByPath(p);if(f instanceof TFile)await this.api('/api/sync/file?device='+encodeURIComponent(this.settings.device)+'&path='+encodeURIComponent(p),'PUT',await this.app.vault.readBinary(f))}for(const p of plan.delete){const f=this.app.vault.getAbstractFileByPath(p);if(f)await this.app.vault.trash(f,true)}for(const p of plan.conflict){const f=this.app.vault.getAbstractFileByPath(p);if(f instanceof TFile)await this.api('/api/sync/conflict?device='+encodeURIComponent(this.settings.device)+'&path='+encodeURIComponent(p),'PUT',await this.app.vault.readBinary(f))}const baseline=await this.hashes();await this.saveData({...d,...this.settings,lastRevision:plan.revision,baseline});const msg=`down ${plan.download.length} up ${plan.upload.length} del ${plan.delete.length} conflict ${plan.conflict.length}`;this.setStatus(plan.conflict.length?'warning '+msg:'ok '+msg);new Notice('Markdown Sync Hub: '+msg)}catch(e){this.setStatus('error');new Notice('Sync failed: '+String(e))}finally{this.syncing=false}}
 onunload(){if(this.timer)window.clearInterval(this.timer)}
}
class Tab extends PluginSettingTab{p:Hub;constructor(a:App,p:Hub){super(a,p);this.p=p}async save(){const d:any=await this.p.loadData()||{};await this.p.saveData({...d,...this.p.settings})}display(){const c=this.containerEl;c.empty();new Setting(c).setName('Server URL').addText(t=>t.setValue(this.p.settings.server).onChange(async v=>{this.p.settings.server=v;await this.save()}));new Setting(c).setName('Sync token').addText(t=>t.setValue(this.p.settings.token).onChange(async v=>{this.p.settings.token=v;await this.save()}));new Setting(c).setName('Device ID').addText(t=>t.setValue(this.p.settings.device).onChange(async v=>{this.p.settings.device=v;await this.save()}));new Setting(c).setName('Sync on startup').addToggle(t=>t.setValue(this.p.settings.startup).onChange(async v=>{this.p.settings.startup=v;await this.save()}));new Setting(c).setName('Auto sync minutes').addText(t=>t.setValue(String(this.p.settings.interval)).onChange(async v=>{this.p.settings.interval=Math.max(0,Number(v)||0);await this.save();this.p.startTimer()}));new Setting(c).setName('Sync now').addButton(b=>b.setButtonText('Sync').onClick(()=>this.p.sync()))}}
